name: fanoos

services:
  fanoos.db:
    container_name: fanoos.db
    image: postgres:16
    restart: on-failure

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fanoos

    ports:
      - "5432:5432"

    volumes:
      - ./.containers/db:/var/lib/postgresql/data
